#!/usr/bin/env python3
"""Run the SAT4J pseudo-Boolean solver with a hard timeout."""
from __future__ import annotations
import argparse
import subprocess
import sys
import time
from pathlib import Path

def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Wrapper around SAT4J with a wall-clock timeout")
    ap.add_argument("--opb", default="schedule.opb", type=Path, help="Path to the .opb file generated by the encoder")
    ap.add_argument("--core-jar", default="org.ow2.sat4j.core-2.3.6.jar", type=Path, help="Path to sat4j core jar")
    ap.add_argument("--pb-jar", default="org.ow2.sat4j.pb-2.3.6.jar", type=Path, help="Path to sat4j pb jar")
    ap.add_argument("--main-class", default="org.sat4j.pb.LanceurPseudo2007", help="Solver entry point")
    ap.add_argument("--timeout", type=int, default=120, help="Time limit in seconds (default: 120s)")
    ap.add_argument("--log", type=Path, default=Path("solver.log"), help="Where to store solver stdout")
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    classpath = f"{args.core_jar}:{args.pb_jar}"
    cmd = [
        "java",
        "-cp",
        classpath,
        args.main_class,
        str(args.opb),
    ]

    started = time.time()
    print("Running:", " ".join(str(c) for c in cmd), file=sys.stderr)
    log_path = Path(args.log)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    with subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        universal_newlines=True,
    ) as proc:
        timed_out = False
        try:
            stdout, _ = proc.communicate(timeout=args.timeout)
        except subprocess.TimeoutExpired:
            timed_out = True
            proc.kill()
            stdout, _ = proc.communicate()
        finally:
            duration = time.time() - started

    log_path.write_text(stdout, encoding="utf-8")
    print(stdout, end="")
    if timed_out:
        print(
            f"[run_solver] Timed out after {args.timeout}s (elapsed {duration:.1f}s). "
            f"Partial output saved to {log_path}",
            file=sys.stderr,
        )
        raise SystemExit(124)

    print(f"[run_solver] Solver finished in {duration:.1f}s (rc={proc.returncode}). Log: {log_path}")
    raise SystemExit(proc.returncode)


if __name__ == "__main__":
    main()
